document.write ("<nav>")
document.write ("<ul class='TiraCafe'>")
document.write("<li class='desbugaCafe'><a href='./index.html'>Home</a></li>")
document.write("<li class='desbugaCafe'><a href='./contato.html'>Contato</a></li>")
document.write("<li class='desbugaCafe'><a href='./about.html'>Sobre</a></li>")
document.write("<li class='dropdown'>")
document.write("<a href='./cadastro.html' class='dropbtn'>Cadastro</a>")   
document.write("<div class='dropdown-content'>")
document.write("<a href='#'>Teste</a>")
document.write("<a href='#'>Teste 2</a>")
document.write("<a href='#'>Teste 3</a>")
document.write("</nav>")